/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.6-dev */

#include "splitflap.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(PB_SplitflapState, PB_SplitflapState, 4)


PB_BIND(PB_SplitflapState_ModuleState, PB_SplitflapState_ModuleState, AUTO)


PB_BIND(PB_Log, PB_Log, 2)


PB_BIND(PB_Ack, PB_Ack, AUTO)


PB_BIND(PB_SupervisorState, PB_SupervisorState, 2)


PB_BIND(PB_SupervisorState_PowerChannelState, PB_SupervisorState_PowerChannelState, AUTO)


PB_BIND(PB_SupervisorState_FaultInfo, PB_SupervisorState_FaultInfo, 2)


PB_BIND(PB_FromSplitflap, PB_FromSplitflap, 4)


PB_BIND(PB_SplitflapCommand, PB_SplitflapCommand, 2)


PB_BIND(PB_SplitflapCommand_ModuleCommand, PB_SplitflapCommand_ModuleCommand, AUTO)


PB_BIND(PB_SplitflapConfig, PB_SplitflapConfig, 2)


PB_BIND(PB_SplitflapConfig_ModuleConfig, PB_SplitflapConfig_ModuleConfig, AUTO)


PB_BIND(PB_RequestState, PB_RequestState, AUTO)


PB_BIND(PB_ToSplitflap, PB_ToSplitflap, 2)







